/* Auto-generated by cbindgen. Do not edit manually. */

#ifndef MATUGEN_FFI_H
#define MATUGEN_FFI_H

/* Warning, this file is autogenerated by cbindgen from src/ffi.rs. Don't manually edit this file. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Releases a `char*` previously returned by [`matugen_extract_colors`],
 * [`matugen_render_template`] or [`matugen_write_output`]. No-op if `ptr` is
 * null. Must be called exactly once per returned pointer.
 *
 * # Safety
 * `ptr` must either be null, or a pointer previously returned by one of this
 * crate's FFI functions that has not already been freed.
 */
void matugen_free_string(char *ptr);

/**
 * Extracts a Material You + base16 palette from an image or an explicit
 * color. See the module docs for the request/response JSON shape and memory
 * ownership rules.
 *
 * # Safety
 * `request_json` must be null or a valid pointer to a NUL-terminated UTF-8
 * C string, valid for the duration of the call.
 */
char *matugen_extract_colors(const char *request_json);

/**
 * Renders a single template to a string. Never touches disk. See the module
 * docs for the request/response JSON shape and memory ownership rules.
 *
 * # Safety
 * `request_json` must be null or a valid pointer to a NUL-terminated UTF-8
 * C string, valid for the duration of the call.
 */
char *matugen_render_template(const char *request_json);

/**
 * Writes rendered content to disk and optionally runs `pre_hook`/`post_hook`.
 * See the module docs for the request/response JSON shape and memory
 * ownership rules.
 *
 * # Safety
 * `request_json` must be null or a valid pointer to a NUL-terminated UTF-8
 * C string, valid for the duration of the call.
 */
char *matugen_write_output(const char *request_json);

/**
 * Extracts colors from an image and renders a template in a single call.
 * The template engine automatically infers the color format from how
 * the template accesses colors (`.red`, `.green`, `.blue`, `.rgb`, `.hsl`,
 * etc.), so callers don't need to worry about matching extraction
 * format to template needs.
 *
 * Returns `{ "ok": true, "rendered": "...", "colors": ..., "base16": ..., "source_color": ... }`.
 *
 * # Safety
 * `request_json` must be null or a valid pointer to a NUL-terminated UTF-8
 * C string, valid for the duration of the call.
 */
char *matugen_render_from_image(const char *request_json);

/**
 * Returns the ranked list of candidate source colors extracted from an image
 * (or image bytes), without picking one. This is the same ranking the CLI's
 * `--show-source-colors` flag prints. See the module docs for the
 * request/response JSON shape and memory ownership rules.
 *
 * # Safety
 * `request_json` must be null or a valid pointer to a NUL-terminated UTF-8
 * C string, valid for the duration of the call.
 */
char *matugen_get_source_colors(const char *request_json);

#endif  /* MATUGEN_FFI_H */
